#!/bin/sh

if [ ! -f /etc/config/placeholder ]; then
  uci set luci.main.lang=zh_cn
  uci set luci.main.mediaurlbase=/luci-static/atmaterial_ci
  uci commit luci

  uci set system.@system[0].timezone=CST-8
  uci set system.@system[0].zonename=Asia/Shanghai
  uci commit system

  uci set fstab.@global[0].anon_mount=1
  uci commit fstab
  sed -i 's/root:.*/root:$1$tTPCBw1t$ldzfp37h5lSpO9VXk4uUE\/:18336:0:99999:7:::/g' /etc/shadow
  uci set network.lan.ipaddr="192.168.0.250"
  uci set network.wan.proto=pppoe
  uci commit network
  
  sed -i '/ipv6.conf/d' /etc/sysctl.conf
  echo net.ipv6.conf.all.disable_ipv6=1 >> /etc/sysctl.conf
  echo net.ipv6.conf.default.disable_ipv6=1 >> /etc/sysctl.conf
  echo net.ipv6.conf.lo.disable_ipv6 = 1 >> /etc/sysctl.conf
  fi
